### ISSUE TITLE
Aborting error while cloning repository

### ISSUE THREAD

**Issue by nununo** [larshp/abapGit#354]
Hello,

I'm getting an aborting error when cloning a repository. It shows an error message in the status line saying: error from RS_FUNCTIONMODULE_INSERT.

And it doesn't process the rest of the objects.

I'd prefer it it would continue creating the rest of the objects and then, in the end, showed a log of what went wrong.

This way I'll have to go and debug to try to figure out what went wrong and how to bypass it.

This is a screen shot after I pressed PULL again after the clone failed:

![image](https://cloud.githubusercontent.com/assets/532049/18719772/aa3c90d2-8020-11e6-9d90-16af495af21e.png)

Thanks!
Nuno

**Comment by larshp** [comment]
yeah, we need to look into some better error handling

you can try setting a breakpoint in https://github.com/larshp/abapGit/blob/master/src/zabapgit_object_fugr.prog.abap#L186 to figure out the real error message

**Comment by nununo** [comment]
Regarding this specific error.. it seems like abapGit is trying to create a FM but I still don't see any function group in the package. Could that be the problem?

**Comment by nununo** [comment]
I put a BP in the beginning of the standard FM with error and went from there...

**Comment by larshp** [comment]
difficult to say, what is the value of `sy-subrc` after the function module has been executed?

**Comment by nununo** [comment]
That's the sad part: SY-SUBRC = 2 ( described as ERROR_MESSAGE )... the actual message inside RS_FUNCTIONMODULE_INSERT is 651(FL) which is "Function module does not exist".

I find it weird because I was gonna try to create the function group manually but found that it already exists after all... but in package $TMP. I'm sure this is a new object... do you first create them in the $TMP and only then move them to the target package?

**Comment by larshp** [comment]
$TMP: no, abapGit tries to place objects in the correct package first. But as always there might be a bug somewhere :smile:

**Comment by nununo** [comment]
I'm late to deliver a complex thing so I found a workaround: since I don't really need to clone that function group now... I reassigned it to another package and removed it from the repository. And now it worked ;)

But I hope in a near future I can help you figure out what is causing the problem!

**Comment by larshp** [comment]
cool, hope abapGit helps you out in whatever you are working on, and does not cause too much trouble.

Appreciate the bug reports

**Comment by nununo** [comment]
I can tell you that... given some recent changes in security policy we have no way to use the transport system to copy objects between our two DEV systems... so... if it weren't for abapGit I'd surely be spending most of my time copying stuff between both systems. I'd probably be using ZSAPLINK but the effort and its limitations are not comparable to abapGit.

So I am the one who needs to thank you! And I'll definitely do my best to help the project ;)

**Comment by pfaller** [comment]
I just ran into the same problem. My suspect is, that it was caused because I used custom DDIC types for the parameters interface of the function modules. This did occur when I was trying to pull the contents from the Git repository into a new SAP system. I think the function group was pulled before the DDIC objects from the Git what lead to failures of  RS_FUNCTIONMODULE_INSERT, since the types of the parameters interface where not present yet. 

After I transported the respective objects to the new system, synchronizing with abapGit works fine even for the function group/modules.

**Comment by larshp** [comment]
okay :smile: thanks for the bug report

can you try reproducing the issue in a public repository? If it is due to custom DDIC types, I guess it should be pretty easy to reproduce a small isolated example

abapGit has a method `prioritize_deser` which handles the sequence of which the objects are deserialized, perhaps it needs adjustments regarding function modules,
https://github.com/larshp/abapGit/blob/d6258d9ea85efd5fcd989c87999dbc3c2dc4880a/src/zabapgit_objects_impl.prog.abap#L576

**Comment by pfaller** [comment]
Hi Lars, I just tried as you suggested. Test repo is at https://github.com/pfaller/abapgit-test. 

Seems that my assumption was wrong, it's probably not the dependencies to DDIC types: I deleted the objects and cloned the github repository into my system again - did work. I'll try if I can provide a reproducable example.   

One other thought: The git repository I tried to clone initially and which failed in the function modules was created with an earlier version of abapGit (from end of Sept.). For importing I was using the current build - do you think this could be a cause?

**Comment by larshp** [comment]
not sure, but everything is possible :smile: I think the FUGR code has been quite stable recently

**Comment by nununo** [comment]
The only improvement I see lacking would be making it able to deal with those dreadful maintenance view function groups and its includes which abapGit is not allowed to create :(

**Comment by larshp** [comment]
@nununo will hopefully get it fixed someday :smile:

**Comment by larshp** [comment]
I am currently experiencing some similar problems, added some extra code to better show the error message:

https://github.com/larshp/abapGit/commit/0add070e67106cee7ffcb4fb51b3750bfa2617d8

It looks like my error occurs due to RFC enabled function modules, @nununo @pfaller are your function modules also RFC enabled?

**Comment by nununo** [comment]
Indeed they are RFC enabled! You're in the right track! ;)

**Comment by larshp** [comment]
Issue reproduced: https://github.com/larshp/FUGR

It happens for RFC enabled function modules, when calling RS_FUNCTIONMODULE_INSERT there is a check that the parameters are valid for RFC, this append for the Active DDIC objects, but currently in abapGit the DDIC objects are not active at this time.

**Comment by pfaller** [comment]
Yes, also in my case it were RFC functions, my symptoms match perfectly to what you describe. I've even tried to reproduce this bug with RFC functions, but didn't observe the bug again - I think I the DDIC object from the parameters were already activated on the system before.

**Comment by larshp** [comment]
try again, this should be solved now

**Comment by larshp** [comment]
closing, please create new issue if the problem persists

**Comment by pfaller** [comment]
Sorry for the late reply. I just set-up a new system where I cloned the same package, now this error didn't occur anymore. Thanks for fixing it!

**Comment by sandraros** [comment]
For people still having this issue ("error in RS_FUNCTIONMODULE_INSERT: 2 FL651"), it may happen normally when a RFC-enabled function module has a parameter which refers to a type which does not exist in the system, for instance you try to import a tool which is intended to be ERP-agnostic but as it was developed on an ERP system, an RFC function may have one of the parameters wrongly refer to a type which exists on ERP only. In that precise case, ask the project owner to correct the issue.
There may be other reasons. For general troubleshooting, **to know the exact error message**, set a break-point right after the call to FUNCTION_CREATE inside RS_FUNCTIONMODULE_INSERT, and check the values in variables FUNCNAME and SY-MSG*. For instance, an invalid type would correspond to a FL385 message with SY-MSGV1 containing the name of the type ("Type &1 is not known or allowed").
